### ISSUE TITLE
Testing initial release

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/sow-rest-UI#3]
Testing the initial release at:
https://github.com/k8-proxy/sow-rest-UI/tree/develop

**Comment by GINAGC** [comment]
Review documentation https://github.com/k8-proxy/sow-rest-UI/blob/main/chart/README.md

review MR https://github.com/k8-proxy/sow-rest-UI/pull/7/files

**Comment by top-dev-mania** [comment]
When I try to check file named "Live Streaming Esimate Proposal .docx", I've got the error such as:
![image](https://user-images.githubusercontent.com/73068626/100833593-e5e48c80-342f-11eb-9ff1-1cb6a431cfc7.png)
Note: file name includes the space(%20).

**Comment by top-dev-mania** [comment]
I checked this issue is fixed.
![image](https://user-images.githubusercontent.com/73068626/100833880-715e1d80-3430-11eb-90e0-30cc0c24f98b.png)
